### ISSUE TITLE
dashing start error

### ISSUE THREAD

**Issue by Mwajeeh54** [daamien/pgDashboard#4]
i got this error with dashing start

bundler: failed to load command: thin (/usr/local/bin/thin)
NameError: uninitialized constant PGError
Did you mean?  TypeError
  /home/mwb/PostgreSQL-Dashboard/jobs/pg_buffers.rb:66:in `rescue in <top (required)>'
  /home/mwb/PostgreSQL-Dashboard/jobs/pg_buffers.rb:16:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
  /var/lib/gems/2.3.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:171:in `block in require_glob'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:170:in `each'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:170:in `require_glob'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:181:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing.rb:3:in `require'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing.rb:3:in `<top (required)>'
  config.ru:1:in `require'
  config.ru:1:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<top (required)>'

**Comment by daamien** [comment]
Hi ! 
Thanks for this report !

At first glance, it looks like a broken depency

Can you post here the list of your packages using;

```
$ gem list
```

**Comment by Mwajeeh54** [comment]
*** LOCAL GEMS ***

addressable (2.5.2)
backports (3.11.3)
bigdecimal (1.2.8)
buftok (0.2.0)
bundler (1.16.1, 1.11.2)
coffee-script (2.2.0)
coffee-script-source (1.12.2)
daemons (1.2.6)
dashing (1.3.7)
did_you_mean (1.0.0)
domain_name (0.5.20180417)
equalizer (0.0.11)
et-orbi (1.1.0)
eventmachine (1.2.5)
execjs (2.0.2)
hike (1.2.3)
http (3.3.0, 3.2.1, 3.2.0)
http-cookie (1.0.3)
http-form_data (2.1.0)
http_parser.rb (0.6.0)
io-console (0.4.5)
json (1.8.3)
memoizable (0.4.2)
minitest (5.8.4)
molinillo (0.4.3)
multi_json (1.13.1)
multipart-post (2.0.0)
mustermann (1.0.2)
naught (1.1.0)
net-http-persistent (2.9.4)
net-telnet (0.1.1)
pg (1.0.0)
power_assert (0.2.7)
psych (2.0.17)
public_suffix (3.0.2)
rack (2.0.5, 1.5.5)
rack-protection (2.0.1, 1.5.5)
rack-test (1.0.0)
rake (10.5.0)
rdoc (4.2.1)
rufus-scheduler (3.4.2, 2.0.24)
sass (3.2.19)
simple_oauth (0.3.1)
sinatra (2.0.1, 1.4.8)
sinatra-contrib (1.4.7)
sprockets (2.10.2)
test-unit (3.1.7)
thin (1.7.2, 1.6.4)
thor (0.20.0, 0.19.1)
thread_safe (0.3.6)
tilt (2.0.8, 1.4.1)
twitter (6.2.0)
tzinfo (1.2.5)
unf (0.1.4)
unf_ext (0.0.7.5)

**Comment by daamien** [comment]
Hi !

Can you try to remove line 27 from the dashboard file (`postgresql.erb`) to check if the same errors occurs on other widgets ?

https://github.com/daamien/PostgreSQL-Dashboard/blob/master/dashboards/postgresql.erb#L27

Thanks,

**Comment by Mwajeeh54** [comment]
Same Error 
dashing start
bundler: failed to load command: thin (/usr/local/bin/thin)
NameError: uninitialized constant PGError
Did you mean?  TypeError
  /home/mwb/PostgreSQL-Dashboard/jobs/pg_buffers.rb:66:in `rescue in <top (required)>'
  /home/mwb/PostgreSQL-Dashboard/jobs/pg_buffers.rb:16:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
  /var/lib/gems/2.3.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:171:in `block in require_glob'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:170:in `each'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:170:in `require_glob'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing/app.rb:181:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing.rb:3:in `require'
  /var/lib/gems/2.3.0/gems/dashing-1.3.7/lib/dashing.rb:3:in `<top (required)>'
  config.ru:1:in `require'
  config.ru:1:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
  /var/lib/gems/2.3.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<top (required)>'

**Comment by Mwajeeh54** [comment]
HI!
see this  below is any missing info 

# PostgreSQL Dashboard config file
{

# Connection
'host' 		=> 'localhost',
'port' 		=> '5432',
'options' 	=> '',  # Backend options 
'tty'  		=> '',     # Obsolete
'dbname' 	=> 'pgdb',
'user'   	=> 'sa',
'password'	=> '*****',

# Scheduler
'freq' 		=> '60s',

# Twitter
# Get your twitter keys & secrets:
# https://dev.twitter.com/docs/auth/tokens-devtwittercom
'tw_consumer_key' 	 => 'YOUR_CONSUMER_KEY',
'tw_consumer_secret' 	 => 'YOUR_CONSUMER_SECRET',
'tw_config.access_token' => 'YOUR_OAUTH_TOKEN',
'tw_access_token_secret' => 'YOUR_OAUTH_SECRET'

}
